### ISSUE TITLE
Webpack 5 fails with TypeError or warns about COMPILATION_ASSETS

### ISSUE THREAD

**Issue by ath0mas** [ahrakio/witty-webpack-declaration-files#4]
Given an existing config running with **Webpack 4** and _@ahrakio/witty-webpack-declaration-files_,
as described in PR #1 the build runs fine but with a warning
```DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead```
(webpack@4.44.2, webpack-cli@3.3.12)

Now with **Webpack 5** the build fails:
`TypeError: compiler.plugin is not a function`
(webpack@5.1.2, webpack-cli@4.0.0)

- solution: merge PR #1, or use fork [@ns0m/witty-webpack-declaration-files](https://github.com/ns0m/witty-webpack-declaration-files)
But,
```
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
```
- no solution found for this warning at the moment

**Comment by ath0mas** [comment]
Debugging with `node --trace-deprecation node_modules/webpack/bin/webpack.js` instead of `webpack`:
```
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.    
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at outputFileToAsset (C:\dev\webpack-example\node_modules\ts-loader\dist\after-compile.js:216:35)
    at outputFilesToAsset (C:\dev\webpack-example\node_modules\ts-loader\dist\after-compile.js:224:13)
    at addDeclarationFilesAsAsset (C:\dev\webpack-example\node_modules\ts-loader\dist\after-compile.js:210:5)      
    at provideDeclarationFilesToWebpack (C:\dev\webpack-example\node_modules\ts-loader\dist\after-compile.js:206:9)
    at C:\dev\webpack-example\node_modules\ts-loader\dist\after-compile.js:30:9
    at Hook.eval [as callAsync] (eval at create (C:\dev\webpack-example\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\dev\webpack-example\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at C:\dev\webpack-example\node_modules\webpack\lib\Compiler.js:986:33
    at C:\dev\webpack-example\node_modules\webpack\lib\Compilation.js:2025:10
    at Hook.eval [as callAsync] (eval at create (C:\dev\webpack-example\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
```

seems linked to https://github.com/TypeStrong/ts-loader/issues/1196, more than this plugin, given the debug trace about `ts-loader\dist\after-compile.js`
(_ts-loader_ 8.0.5)

**Comment by ath0mas** [comment]
Debugging with `node --trace-deprecation node_modules/webpack/bin/webpack.js` instead of `webpack`:
```
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.    
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at outputFileToAsset (C:\dev\webpack-example\node_modules\ts-loader\dist\after-compile.js:216:35)
    at outputFilesToAsset (C:\dev\webpack-example\node_modules\ts-loader\dist\after-compile.js:224:13)
    at addDeclarationFilesAsAsset (C:\dev\webpack-example\node_modules\ts-loader\dist\after-compile.js:210:5)      
    at provideDeclarationFilesToWebpack (C:\dev\webpack-example\node_modules\ts-loader\dist\after-compile.js:206:9)
    at C:\dev\webpack-example\node_modules\ts-loader\dist\after-compile.js:30:9
    at Hook.eval [as callAsync] (eval at create (C:\dev\webpack-example\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\dev\webpack-example\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at C:\dev\webpack-example\node_modules\webpack\lib\Compiler.js:986:33
    at C:\dev\webpack-example\node_modules\webpack\lib\Compilation.js:2025:10
    at Hook.eval [as callAsync] (eval at create (C:\dev\webpack-example\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
```

**Comment by ath0mas** [comment]
_ts-loader_ fixed previous warning in `ts-loader\dist\after-compile.js` with version 8.0.6 👍 

but now same warning appears for this plugin in `witty-webpack-declaration-files\src\index.js`:
```
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at C:\MyWorks\ns0m\witty-webpack-declaration-files\example\node_modules\@ns0m\witty-webpack-declaration-files\src\index.js:64:43
    at Array.forEach (<anonymous>)
    at C:\MyWorks\ns0m\witty-webpack-declaration-files\example\node_modules\@ns0m\witty-webpack-declaration-files\src\index.js:63:20
    at Hook.eval [as callAsync] (eval at create (C:\MyWorks\ns0m\witty-webpack-declaration-files\example\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\MyWorks\ns0m\witty-webpack-declaration-files\example\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.emitAssets (C:\MyWorks\ns0m\witty-webpack-declaration-files\example\node_modules\webpack\lib\Compiler.js:739:19)
    at C:\MyWorks\ns0m\witty-webpack-declaration-files\example\node_modules\webpack\lib\Compiler.js:398:10
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
